spring.application.name=DevopsWebApp

spring.datasource.url=jdbc:sqlite:C:/Users/Suraksha/GWEnterpriseSWCourseFinal/users.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false